// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7wZb2tO1-Fs6GbDADUSTs2Qs3w08Hovw',
    appId: '1:406099696497:web:87e25e51afe982cd3574d0',
    messagingSenderId: '406099696497',
    projectId: 'kammun-app',
    authDomain: 'kammun-app.firebaseapp.com',
    databaseURL: 'https://kammun-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kammun-app.appspot.com',
    measurementId: 'G-JN95N1JV2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7386Ys0K2XuSmQ79D2e64eEF_0wFUziU',
    appId: '1:501860290616:android:ef6ae7e1b942db069c56cd',
    messagingSenderId: '501860290616',
    projectId: 'kammun-app',
    // databaseURL:
    //     'https://kammun-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kammun-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwvRVr4Yk5vyl7RqThpfmoOpX-YihnpOg',
    appId: '1:501860290616:ios:433e91fd777f1ac49c56cd',
    messagingSenderId: '501860290616',
    projectId: 'kammun-app',
    // databaseURL:
    //     'https://kammun-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kammun-app.appspot.com',
    androidClientId: '501860290616-sljn7hmd2ft43i3i5an488ioe1hjf2vt.apps.googleusercontent.com',
    // iosClientId:
    //     '406099696497-taeapvle10rf355ljcvq5dt134mkghmp.apps.googleusercontent.com',
    iosBundleId: 'com.kammun.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDooSUGSf63Ghq02_iIhtnmwMDs4HlWS6c',
    appId: '1:406099696497:ios:acd9c8e17b5e620e3574d0',
    messagingSenderId: '406099696497',
    projectId: 'kammun-app',
    databaseURL: 'https://kammun-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kammun-app.appspot.com',
    androidClientId: '406099696497-tvtvuiqogct1gs1s6lh114jeps7hpjm5.apps.googleusercontent.com',
    iosClientId: '406099696497-taeapvle10rf355ljcvq5dt134mkghmp.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.plugins.firebase.tests',
  );
}
