// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRXJRq6H13ge20clkPzJEkg90DKCIknF8',
    appId: '1:628575156190:web:35e6381db6de7fbad58f4f',
    messagingSenderId: '628575156190',
    projectId: 'kammun-user-v3',
    authDomain: 'kammun-user-v3.firebaseapp.com',
    storageBucket: 'kammun-user-v3.appspot.com',
    measurementId: 'G-PPXL93QF9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqQfwe7blsXH7G40V1MkjCwTarkvSvjDQ',
    appId: '1:628575156190:android:7a772ef4c184f807d58f4f',
    messagingSenderId: '628575156190',
    projectId: 'kammun-user-v3',
    storageBucket: 'kammun-user-v3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK11NUuGFk1H3VP028AYux1YKirUWzH_Y',
    appId: '1:628575156190:ios:d846ab2cddbc1612d58f4f',
    messagingSenderId: '628575156190',
    projectId: 'kammun-user-v3',
    storageBucket: 'kammun-user-v3.appspot.com',
    iosClientId: '628575156190-som0k208ldviejmls4k0u6ccvc8jd7e1.apps.googleusercontent.com',
    iosBundleId: 'com.kammun.app',
  );
}
